epochs: 10
batch_size: 64
lr: 0.0001
use_scheduler: false
output_dir: ./outputs/fmnist
data_path: ./data
dataset: FashionMNIST

DATA:
  DATASET: FashionMNIST
  IMG_SIZE: 32
  NUM_CLASSES: 10
  DATA_PATH: ./data
